### ISSUE TITLE
failed check in morton_encoding.h in Debug mode in panoptic.

### ISSUE THREAD

**Issue by tarquai** [ethz-asl/wavemap#32]
**Describe the bug**
running the demo panoptic database IN DEBUG MODE (not the default release), as described in the demo section, causes a failed     DCHECK_GE

**To Reproduce**
Run the panoptic demo as described in the installation, but with one difference:
instead of "catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release"
replace Release with Debug.

**Expected behaviour**
There should be no error logs in Debug mode (similar to Release)

**Observed outcome**
here is the error log:
_```
F0912 12:48:46.156935 30960 morton_encoding.h:50] Check failed: index[dim_idx] >= 0 (-2 vs. 0) 
*** Check failure stack trace: ***
_F0F0F0F0909121121 12:48F:464604.15100:012 012156929 48    146 12: 48:46.156939 30957 309610959   30956n_encoding.h::m50ton_encoding.h50] 50] eck failed: index[dim_idx] >index[dim_idx]
ndex[dim_idx]Chindex[dim_idx] >= 0 (-4 vs. 0)  
dex[dim_idx] >= 0 (-2 vs. 0) F0912 12:48:46.156991 30951 morton_encoding.h:50] Check failed: index[dim_idx] >= 0 (-5 vs. 0) F0912 12:48:46.157212 30953 morton_encoding.h:50] Check failed: index[dim_idx] >= 0 (-2 vs. 0) F0912 12:48:46.157250 30952 morton_encoding.h:50] Check failed: index[dim_idx] >= 0 (-4 vs. 0) F0912 12:48:46.157334     F309630 morton_encoding.h 9:12 5012Ch:ck failed: index[dim_idx] >= 0 (-3 vs. 0) 48:46.157335 30949 morton_encoding.h:50] Check failed: index[dim_idx] >= 0 (-1 vs. 0) F0912 12:48:46.157366 30964 morton_encoding.h:50] Check failed: index[dim_idx] >= 0 (-3 vs. 0) F0912 12:48:46.157377 30955 morton_encoding.h:50] Check failed: index[dim_idx] >= 0 (-2 vs. 0) F0912 12:48:46.157466 30950 morton_encoding.h:50] Check failed: index[dim_idx] >= 0 (-5 vs. 0) F0912 12:48:46.157855 30962 morton_encoding.h:50] Check failed: index[dim_idx] >= 0 (-3 vs. 0)_
```_ 

**System information (please complete if relevant):**
 - CPU:  i9-10980HK
 - RAM: [ 32GB]
 - OS: [ Ubuntu 20.04]
 - Wavemap
   - install: Docker
   - version: [e.g.,  v1.5.1]

**Comment by victorreijgwart** [comment]
Hi @tarquai, thank you for reporting this bug! Please excuse the brief reply; we're very busy with some upcoming deadlines.

The DCHECK that fails in the error log you shared is there because our implementation of Morton numbers does not support negative indices. Specifically, the sign is not preserved when converting indices to Morton numbers and back (Index -> Morton -> Index).

I will look into the issue and prepare a patch next week. In the meantime, the error should be safe to ignore since wavemap currently only uses one-way conversions (Index -> Morton) and the Morton numbers are only used to compute relative offsets. I'd suggest temporarily removing the DCHECK or compiling wavemap in release mode.

**Comment by tarquai** [comment]
Thanks for the quick replay.
I am indeed using debug mode just to understand the code (which is high quality!), and nothing more.

**Comment by victorreijgwart** [comment]
Thanks! I'll update this issue once the patch is ready.

**Comment by victorreijgwart** [comment]
Hi @tarquai, the issue should be solved by the changes on the [fix/failing_dchecks](https://github.com/ethz-asl/wavemap/tree/fix/failing_dchecks) branch. We'll include it in the next upcoming release.
